"""Rust-backed SVG path editing, optimization, tracing, and centerline APIs."""

from .centerline import CenterlineOptions, RasterContext, centerline_path_data, centerline_svg_text
from .geometry import (
    circle_to_path,
    ellipse_to_path,
    get_kappa,
    get_precision,
    identity,
    line_to_path,
    matrix_to_3x3,
    multiply_matrices,
    polygon_to_path,
    polyline_to_path,
    rect_to_path,
    rotate_2d,
    scale_2d,
    set_precision,
    transform_2d,
    transform_geometry_path,
    translate_2d,
)
from .inspect_svg import (
    convert_shapes_svg,
    flatten_svg,
    get_svg_info,
    inline_styles_svg,
    sanitize_svg,
    to_plain_svg,
    validate_svg,
    validate_svg_async,
)
from .measure import metrics_json, path_bbox, path_length, path_metrics, point_at_length, svg_metrics
from .pathdata import PathData, parse_path, path_to_absolute, path_to_cubics, path_to_relative, path_to_string, transform_path
from .path_utils import (
    auto_round,
    cross,
    detect_polyline_accuracy,
    filled_loops,
    format_number,
    normalize_color,
    optimize_path_data,
    point_distance,
    point_line_distance,
    polygon_area,
    polygon_centroid,
    polyline_lengths,
    polyline_subpaths,
    radial_centerline_candidate,
    ray_intersections,
    remove_collinear_points,
    round_to,
    serialize_polyline_subpaths,
    serialize_smooth_closed,
    simplify_closed_points,
    simplify_points,
    simplify_radial_distance,
    simplify_rdp,
    stitch_subpaths,
    turn_stats,
)
from .raster_trace import Image, TraceOptions, trace_image, trace_image_components, trace_png, trace_png_components
from .svg_optimize import BUILTIN_PLUGINS, OptimizeOptions, PluginSpec, optimize_svg
from .vtracer_trace import VTracerOptions, trace_image_vtracer
from .viewport import fit_viewbox_svg, resize_svg, set_viewbox_svg

__all__ = [
    "BUILTIN_PLUGINS",
    "CenterlineOptions",
    "Image",
    "OptimizeOptions",
    "PathData",
    "PluginSpec",
    "RasterContext",
    "TraceOptions",
    "VTracerOptions",
    "auto_round",
    "circle_to_path",
    "centerline_path_data",
    "centerline_svg_text",
    "convert_shapes_svg",
    "cross",
    "detect_polyline_accuracy",
    "ellipse_to_path",
    "filled_loops",
    "format_number",
    "fit_viewbox_svg",
    "flatten_svg",
    "get_kappa",
    "get_precision",
    "get_svg_info",
    "identity",
    "inline_styles_svg",
    "line_to_path",
    "matrix_to_3x3",
    "metrics_json",
    "multiply_matrices",
    "normalize_color",
    "optimize_svg",
    "optimize_path_data",
    "parse_path",
    "path_bbox",
    "path_length",
    "path_metrics",
    "path_to_absolute",
    "path_to_cubics",
    "path_to_relative",
    "path_to_string",
    "point_at_length",
    "point_distance",
    "point_line_distance",
    "polygon_to_path",
    "polygon_area",
    "polygon_centroid",
    "polyline_lengths",
    "polyline_to_path",
    "polyline_subpaths",
    "radial_centerline_candidate",
    "ray_intersections",
    "rect_to_path",
    "remove_collinear_points",
    "resize_svg",
    "rotate_2d",
    "round_to",
    "sanitize_svg",
    "scale_2d",
    "serialize_polyline_subpaths",
    "serialize_smooth_closed",
    "set_precision",
    "set_viewbox_svg",
    "simplify_closed_points",
    "simplify_points",
    "simplify_radial_distance",
    "simplify_rdp",
    "stitch_subpaths",
    "svg_metrics",
    "to_plain_svg",
    "trace_image",
    "trace_image_components",
    "trace_image_vtracer",
    "trace_png",
    "trace_png_components",
    "transform_2d",
    "transform_geometry_path",
    "transform_path",
    "translate_2d",
    "turn_stats",
    "validate_svg",
    "validate_svg_async",
]

from . import _svgo as _rust

__version__ = getattr(_rust, "__version__", "0.4.0")

del _rust
